dependencies {
    implementation project(':model')
    implementation project(':usecase')
    implementation 'org.springframework:spring-context'
    implementation 'software.amazon.awssdk:ses:2.20.86'
    // https://mvnrepository.com/artifact/org.thymeleaf/thymeleaf
    implementation 'org.thymeleaf:thymeleaf:3.1.2.RELEASE'
}
